apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-cluster"
  namespace: "cluster-services"
spec:
  configuration:
    users:
      default/networks/ip: "::/0"
    zookeeper:
      disabled: true
    keeper:
      enabled: true
    clusters:
      - name: "default"
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: clickhouse-template
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse
              image: "clickhouse/clickhouse-server:25.3"
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: clickhouse-storage
              emptyDir: {}
