apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace : {{ .Values.namespace }}
data:
  ENV: "{{ .Values.env }}"
  IS_DRY_RUN: "{{ .Values.isDryRun }}"
  FRONTEND_ID: "{{ .Values.frontendId }}"
  SCHEDULE_USERS_INTERVAL: "{{ .Values.scheduleUsersInterval }}"
  MAX_ACTIVE_USERS: "{{ .Values.maxActiveUsers }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.bootstrapServers }}"
  KAFKA_OUTPUT_TOPIC: "{{ .Values.kafka.outputTopic }}"
