apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  ENV: "{{ .Values.env }}"
  JOB_NAME: "{{ .Values.jobName }}"

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.bootstrapServers }}"
  KAFKA_CLICK_STREAM_TOPIC: "{{ .Values.kafka.clickStreamTopic }}"
  KAFKA_SESSIONS_TOPIC: "{{ .Values.kafka.sessionsTopic }}"
  KAFKA_ATTRIBUTED_ORDERS_TOPIC: "{{ .Values.kafka.attributedOrdersTopic }}"

  # Session processor
  SESSION_INACTIVITY_GAP: "{{ .Values.sessionProcessor.maxSessionLookback }}"
  SESSION_PROCESSOR_SESSIONS_CACHE_TTL: "{{ .Values.sessionProcessor.sessionsCacheTTL }}"

  # Out of order events
  MAX_OUT_OF_ORDERNESS: "PT3M"
  ORDERING_WINDOW_SIZE: "PT5S"
