name: Build and Push Flink Job Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'flink-job/**'
  pull_request:
    paths:
      - 'flink-job/**'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: nadberezny/flink-sessionizer

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nadberezny
          password: ${{ secrets.NADBEREZNY_DOCKER_TOKEN }}

      - name: Build and push flink-job image
        run: |
          ./gradlew :flink-job:dockerBuildAndPushImage -PdockerPlatform=linux/amd64 -PdockerTag=latest    
